<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZULF-PC" name="com.employeeapi.testCases.TC002_Get_Single_Employee_Record" tests="7" failures="1" timestamp="4 Aug 2019 17:36:28 GMT" time="0.061" errors="0">
  <testcase name="checkResponseTime" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkResposeBody" time="0.035" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.employeeapi.testCases.TC002_Get_Single_Employee_Record.checkResposeBody(TC002_Get_Single_Employee_Record.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase name="checkstatusLine" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkserverType" time="0.002" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkContentType" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkContentLenght" time="0.020" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
</testsuite> <!-- com.employeeapi.testCases.TC002_Get_Single_Employee_Record -->
